config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {registrations: "registrations"}
  resources :initiatives
  root 'initiatives#main_page'
  get '/filter', to: 'initiatives#filter'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/initiative.rb
class Initiative < ApplicationRecord
  validates :name, presence: true
  validates :institution, presence:true
  validates :address, presence:true
  validates :city, presence:true
  validates :state, presence:true
  validates :responsible, presence:true
  validates :responsible_email, presence:true, :email_format => {:message => 'invalid e-mail address'}
  validates :responsible_phone, presence:true, numericality: { only_integer: true}, length: {minimum: 10, maximum: 15}

  geocoded_by      :get_full_address # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def get_full_address
     [address, city, state].compact.join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    initiatives_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  before_action :set_initiative, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:main_page, :filter, :index, :show]
  
  #root
  def main_page
    @initiatives = Initiative.all
  end

  # GET /filter/query
  def filter
    if params[:query]
     q = params[:query].downcase
     query_string = "lower(initiatives.name) like '%#{q}%'"
     query_string = "#{query_string } or lower(initiatives.city) like '%#{q}%'"
     query_string = "#{query_string } or lower(initiatives.responsible) like '%#{q}%'"
     query_string = "#{query_string } or lower(initiatives.institution) like '%#{q}%'"
     
     render :json => Initiative.where(query_string).to_json
    else
     render :json => Initiative.all.to_json
    end
  end
  
  # GET /initiatives
  # GET /initiatives.json
  def index
    @initiatives = Initiative.all
  end
  
  # GET /initiatives/1
  # GET /initiatives/1.json
  def show
  end

  # GET /initiatives/new
  def new
    @initiative = Initiative.new
  end

  # GET /initiatives/1/edit
  def edit
  end

  # POST /initiatives
  # POST /initiatives.json
  def create
    @initiative = Initiative.new(initiative_params)

    respond_to do |format|
      if @initiative.save
        format.html { redirect_to @initiative, notice: 'Initiative was successfully created.' }
        format.json { render :show, status: :created, location: @initiative }
        #Register in platform

      else
        format.html { render :new }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /initiatives/1
  # PATCH/PUT /initiatives/1.json
  def update
    respond_to do |format|
      if @initiative.update(initiative_params)
        format.html { redirect_to @initiative, notice: 'Initiative was successfully updated.' }
        format.json { render :show, status: :ok, location: @initiative }
      else
        format.html { render :edit }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initiatives/1
  # DELETE /initiatives/1.json
  def destroy
    @initiative.destroy
    respond_to do |format|
      format.html { redirect_to initiatives_url, notice: 'Initiative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_initiative
      @initiative = Initiative.find(params[:id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
    def initiative_params
      params.require(:initiative).permit(:name, :institution, :address, :city, :state, :latitude, :longitude, :responsible, :responsible_email, :responsible_phone)
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]
  
  protected

  def one_user_registered?
    if ((Admin.count == 1) & (admin_signed_in?))
      redirect_to initiatives_url
    elsif Admin.count >= 1
      redirect_to initiatives_url
    end  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/views/initiatives/_form.html.erb
<%= form_for(initiative) do |f| %>
  <% if initiative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(initiative.errors.count, "error") %> prohibited this initiative from being saved:</h2>

      <ul>
      <% initiative.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :institution %>
    <%= f.text_field :institution %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  
  
  <div class="field">
    <%= f.label :responsible %>
    <%= f.text_field :responsible %>
  </div>

  <div class="field">
    <%= f.label :responsible_email %>
    <%= f.text_field :responsible_email %>
  </div>

  <div class="field">
    <%= f.label :responsible_phone %>
    <%= f.text_field :responsible_phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/initiatives/edit.html.erb
<h1>Editing Initiative</h1>

<%= render 'form', initiative: @initiative %>

<%= link_to 'Show', @initiative %> |
<%= link_to 'Back', initiatives_path, method: :get %>

app/views/initiatives/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
   <h2 id="lb_initiatives">Initiatives</h2>
   <% if admin_signed_in? %>
   	<span id="btn_logout" class="btn btn-primary"><%= link_to 'Log out', destroy_admin_session_url, method: :delete %></span>
   <% else %>
   	<span id="btn_logout" class="btn btn-primary"><%= link_to 'Log in', new_admin_session_url, method: :get %></span>
   <% end %>
   <div id="initiative_view_panel" class="table-responsive">
   <table class="table table-hover">
     <thead>
       <tr>
         <th>Name</th>
         <th>Institution</th>
         <th>Address</th>
         <th>City</th>
         <th>State</th>
         <th>Responsible</th>
         <th>Responsible email</th>
         <th>Responsible phone</th>
         <th class="latitude">Latitude</th>
         <th class="longitude">Longitude</th>
         <th colspan="3"></th>
       </tr>
     </thead>

     <tbody id="initiatives">
       <% @initiatives.each do |initiative| %>
         <tr>
           <td class="ini_name"><%= initiative.name %></td>
           <td class="ini_instituition"><%= initiative.institution %></td>
           <td class="ini_address"><%= initiative.address %></td>
           <td class="ini_city"><%= initiative.city %></td>
           <td class="ini_state"><%= initiative.state %></td>
           <td class="ini_res"><%= initiative.responsible %></td>
           <td class="ini_res_email"><%= initiative.responsible_email %></td>
           <td class="ini_res_phone"><%= initiative.responsible_phone %></td>
           <td class="latitude"><%= initiative.latitude %></td>
           <td class="longitude"><%= initiative.longitude %></td>
           <td><%= link_to 'Show', initiative %></td>
           <td><%= link_to 'Edit', edit_initiative_path(initiative) %></td>
           <td><%= link_to 'Destroy', initiative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
       <% end %>
     </tbody>
   </table>
   <%= link_to 'Create New Initiative', new_initiative_path %>
   </div>
</div>
<div id="mapcontainer"></div>

app/views/initiatives/main_page.html.erb
<%= stylesheet_link_tag "main_page" %>
<div class="container-fluid">
    <h2 id="main_title">Smart Cities Initiatives</h2>
    <form id="search_initiative" action="/filter" method="GET" class="search_container container-fluid">
      <input type="text" name="query" id="txt_user_query" class="form-control" placeholder="Search by Project name, Institution, City or Responsible Person" />
      <input id="btn_search" class="btn btn-primary" type="submit" value="Search " />
    </form>
</div>
<div id="mapcontainer"></div>

app/views/initiatives/new.html.erb
<h1>New Initiative</h1>

<%= render 'form', initiative: @initiative %>

<%= link_to 'Back', initiatives_path %>

app/views/initiatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @initiative.name %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @initiative.institution %>
</p>

<p>
  <strong>Address:</strong>
  <%= @initiative.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @initiative.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @initiative.state %>
</p>

<p>
  <strong>Responsible:</strong>
  <%= @initiative.responsible %>
</p>

<p>
  <strong>Responsible email:</strong>
  <%= @initiative.responsible_email %>
</p>

<p>
  <strong>Responsible phone:</strong>
  <%= @initiative.responsible_phone %>
</p>

<%= link_to 'Edit', edit_initiative_path(@initiative) %> |
<%= link_to 'Back', initiatives_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sampasmartmap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>